import {Signup} from '../ui';

export default {
  IS_FIRST_TIME: 'IS_FIRST_TIME',
  CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
  NO_INTERNET: 'NO_INTERNET',
  USER_DATA: 'USER_DATA',
  LOGIN: 'LOGIN',
  SOCIAL_LOGIN_DATA: 'SOCIAL_LOGIN_DATA',
  SELECTED_INVITED_USER: 'SELECTED_INVITED_USER',
  JOIN_POST_REDUX: 'JOIN_POST_REDUX',
  SAVE_SIGNUP_DATA: 'SAVE_SIGNUP_DATA',
  save_messaag: 'save_messaag',
};
