export default {
  ic_facebook: require('../assets/images/ic_facebook.png'),
  car_ic: require('../assets/images/car_ic.png'),
  splash_logo: require('../assets/images/splash_logo.png'),
  onboard_logo: require('../assets/images/onboard_logo.png'),
  login_bg: require('../assets/images/login_bg.png'),
  apple_ic: require('../assets/images/apple_ic.png'),
  google_ic: require('../assets/images/google_ic.png'),
  facebook_ic: require('../assets/images/facebook_ic.png'),
  dropdown_ic: require('../assets/images/dropdown_ic.png'),
  check_ic: require('../assets/images/check_ic.png'),
  back_ic: require('../assets/images/back_ic.png'),
  side_menu_ic: require('../assets/images/side_menu_ic.png'),
  side_home_ic: require('../assets/images/side_home_ic.png'),
  profile_ic: require('../assets/images/profile_ic.png'),
  history_ic: require('../assets/images/history_ic.png'),
  offers_ic: require('../assets/images/offers_ic.png'),
  notification_ic: require('../assets/images/notification_ic.png'),
  support_ic: require('../assets/images/support_ic.png'),
  logout_ic: require('../assets/images/logout_ic.png'),
  menu_close_ic: require('../assets/images/menu_close_ic.png'),
  new_ride_ic: require('../assets/images/new_ride_ic.png'),
  home_ic: require('../assets/images/home_ic.png'),
  office_ic: require('../assets/images/office_ic.png'),
  small_loc_ic: require('../assets/images/small_loc_ic.png'),
  small_navigation_ic: require('../assets/images/small_navigation_ic.png'),
  location_ic: require('../assets/images/location_ic.png'),
  navigation_ic: require('../assets/images/navigation_ic.png'),
  sedan_ic: require('../assets/images/sedan_ic.png'),
  money_ic: require('../assets/images/money_ic.png'),
  down_arrow_ic: require('../assets/images/down_arrow_ic.png'),
  cross_ic: require('../assets/images/cross_ic.png'),
  cash_ic: require('../assets/images/cash_ic.png'),
  slider_ic: require('../assets/images/slider_ic.png'),
  
  
};
